### ISSUE TITLE
executeSQL return values

### ISSUE THREAD

**Issue by mrchimp** [mrchimp/core#3]
executeSQL() returns an array of data from fetchAll() which is fine for select statements but for insert/update/delete we really want to return the result of execute() as that returns a true or false value.

In my previous database class (I can send you a copy of to look at if you like) I had get_row(), get_recordset() and get_value() for select statements (though these could have been combined into one) as well as insert() which returned the auto-incremented id of the last record inserted and execute() for all other sql queries which returned the number of rows affected.

Really you only need number of rows affected with update and delete queries, create/drop should return true/false.

Hmm.

**Comment by danimalweb** [comment]
Yeah I've been meaning to adapt that function for sometime so it can be used for insert/update/delete etc. but as my site only uses a select I've not got round to it. Send a your previous db class and I'll adapt it tomorrow and sent to you for some testing with an example  file.

Dan

**Comment by mrchimp** [comment]
Well I'm not sure my way is the best but it's a good start. I'll send it over for reference.

I think something like this:

SELECT
    select() - returns array of results

DELETE
UPDATE
    update() - returns number of rows affected. Maybe make delete() a separate function

INSERT
    insert() - returns id of last inserted

CREATE TABLE
ALTER TABLE
and others...
    execute() - generic function, returns boolean 

Here's some other guy's attempt: http://stackoverflow.com/questions/6740153/simple-pdo-wrapper

**Comment by mrchimp** [comment]
In fact it could make using core a lot easier if we have a generic execute() function and then pass it off to other functions depending on the first word of the query.

Might be simpler, might just be confusing as you'd get mixed return values...

**Comment by danimalweb** [comment]
That's what I was thinking. I'm ok with a mixed return value as long as its documented which it will be. It doesn't necessary have to be based on the first word, could be a parameter.

Can you email me the previous db class? 

Thanks

**Comment by mrchimp** [comment]
Project is dead.
